<html>
<body>
<?php
include('config.phtml');
if(isset($_POST['submit']))
{
$username=mysql_real_escape_string($_POST['username']);
$password=mysql_real_escape_string($_POST['password']);
$query1=mysql_query("insert into members values('','$username','$password')");
echo "insert into members values('','$username','$password')";
if($query1)
{
header("location:list");
}
}
?>
<fieldset style="width:300px;">
<form method="post" action="">
Username: <input type="text" name="username"><br>
Password: <input type="text" name="password"><br>
<br>
<input type="submit" name="submit">
</form>
</fieldset>
</body>
</html>